### ISSUE TITLE
EDA) 데이터 EDA

### ISSUE THREAD

**Issue by nonegom** [boostcampaitech3/level2-mrc-level2-nlp-09#4]
**Task 수행이유**: 이번 Task에는 Label이 없기는 하지만, 텍스트 데이터의 길이나 수, 결측치 등을 확인할 필요가 있다.

**목표**: EDA를 통해 데이터의 형태, 문장길이, 데이터 수, 결측치 등을 파악하고자 한다.

**Comment by wogkr810** [comment]
[EDA 관련 노션](https://www.notion.so/jaehahk/EDA-9943b72eed39442398cec8c3fc4a80c0)
